services:
  linkedout-api-test:
    container_name: linkedout-api-test
    build:
      context: ./
      target: base
    entrypoint: ['./docker-entrypoint.test.sh']
    env_file:
      - .env.test
    environment:
      NODE_ENV: dev-test
      DB_HOST: linkedout-db
      DB_PORT: 5432
      DB_USER: linkedout
      DB_PASSWORD: linkedout
      DB_NAME: linkedouttest
    volumes:
      - .:/home/node
    image: linkedout-api:nestjs
    depends_on:
      - linkedout-db

  linkedout-db:
    image: postgres:14.1-alpine
    container_name: linkedout-db-postgresql
    restart: always
    environment:
      - POSTGRES_USER=linkedout
      - POSTGRES_PASSWORD=linkedout
    ports:
      - '5432:5432'
    command:
      - 'postgres'
      - '-c'
      - 'log_temp_files=10240'
      - '-c'
      - 'shared_buffers=3GB'

volumes:
  linkedout-db:
    driver: local
