services:
  api-test:
    container_name: api-test
    build:
      context: ./
      target: base
    entrypoint: ['./docker-entrypoint.test.sh']
    env_file:
      - .env.test
    environment:
      NODE_ENV: dev-test
      DB_HOST: db-test
      DB_PORT: 5432
      DB_USER: entourage_pro
      DB_PASSWORD: entourage_pro
      DB_NAME: entourage_pro_test
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      - db-test

  db-test:
    container_name: db-test
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=entourage_pro
      - POSTGRES_PASSWORD=entourage_pro
    ports:
      - '5433:5432'
    command:
      - 'postgres'
      - '-c'
      - 'log_temp_files=10240'
      - '-c'
      - 'shared_buffers=3GB'

volumes:
  db-test:
    driver: local
