services:
  ## ENTOURAGE PRO BACKEND API
  api:
    container_name: api
    build:
      context: ./
      target: base
      args:
        NODE_VERSION: 20.19.1
    volumes:
      - .:/home/node
      - /home/node/node_modules
    ports:
      - '3002:3002'
    env_file:
      - .env
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: entourage_pro
      DB_PASSWORD: entourage_pro
      DB_NAME: entourage_pro
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  db:
    container_name: db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=entourage_pro
      - POSTGRES_PASSWORD=entourage_pro
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    command:
      - 'postgres'
      - '-c'
      - 'log_temp_files=10240'
      - '-c'
      - 'shared_buffers=3GB'
  ## ENTOURAGE PRO BACKEND CACHE
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local
