services:
  ## ENTOURAGE PRO BACKEND WORKER
  worker:
    container_name: worker
    build:
      context: ./
      target: base
      args:
        NODE_VERSION: 20.19.1
    entrypoint: ['./docker-entrypoint.worker.sh']
    volumes:
      - .:/home/node
      - /home/node/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: entourage_pro
      DB_PASSWORD: entourage_pro
      DB_NAME: entourage_pro
      DD_AGENT_HOST: datadog
    depends_on:
      - db
      - redis
