import { FilterConstant } from 'src/utils/types';
import { DepartmentCode } from 'src/utils/types/departments.types';
import { ZoneName } from 'src/utils/types/zones.types';

export type DepartmentType = {
  name: string;
  zone: ZoneName;
  region: string;
  code: DepartmentCode;
};

export const Departments = [
  {
    name: 'Ain (01)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Ain,
  },
  {
    name: 'Aisne (02)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Aisne,
  },
  {
    name: 'Allier (03)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Allier,
  },
  {
    name: 'Alpes-de-Haute-Provence (04)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.AlpesDeHauteProvence,
  },
  {
    name: 'Hautes-Alpes (05)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.HautesAlpes,
  },
  {
    name: 'Alpes-Maritimes (06)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.AlpesMaritimes,
  },
  {
    name: 'Ardèche (07)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Ardeche,
  },
  {
    name: 'Ardennes (08)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Ardennes,
  },
  {
    name: 'Ariège (09)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Ariege,
  },
  {
    name: 'Aube (10)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Aube,
  },
  {
    name: 'Aude (11)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Aude,
  },
  {
    name: 'Aveyron (12)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Aveyron,
  },
  {
    name: 'Bouches-du-Rhône (13)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.BouchesDuRhone,
  },
  {
    name: 'Calvados (14)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Calvados,
  },
  {
    name: 'Cantal (15)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Cantal,
  },
  {
    name: 'Charente (16)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Charente,
  },
  {
    name: 'Charente-Maritime (17)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.CharenteMaritime,
  },
  {
    name: 'Cher (18)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.Cher,
  },
  {
    name: 'Corrèze (19)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Correze,
  },
  {
    name: "Côte-d'Or (21)",
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.CoteDOr,
  },
  {
    name: "Côtes-d'Armor (22)",
    zone: ZoneName.BRETAGNE,
    region: 'Bretagne',
    code: DepartmentCode.CotesDArmor,
  },
  {
    name: 'Creuse (23)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Creuse,
  },
  {
    name: 'Dordogne (24)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Dordogne,
  },
  {
    name: 'Doubs (25)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Doubs,
  },
  {
    name: 'Drôme (26)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Drome,
  },
  {
    name: 'Eure (27)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Eure,
  },
  {
    name: 'Eure-et-Loir (28)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.EureEtLoir,
  },
  {
    name: 'Finistère (29)',
    zone: ZoneName.BRETAGNE,
    region: 'Bretagne',
    code: DepartmentCode.Finistere,
  },
  {
    name: 'Corse-du-Sud (2A)',
    zone: ZoneName.HZ,
    region: 'Corse',
    code: DepartmentCode.CorseDuSud,
  },
  {
    name: 'Haute-Corse (2B)',
    zone: ZoneName.HZ,
    region: 'Corse',
    code: DepartmentCode.HauteCorse,
  },
  {
    name: 'Gard (30)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Gard,
  },
  {
    name: 'Haute-Garonne (31)',
    zone: ZoneName.SUDOUEST,
    region: 'Occitanie',
    code: DepartmentCode.HauteGaronne,
  },
  {
    name: 'Gers (32)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Gers,
  },
  {
    name: 'Gironde (33)',
    zone: ZoneName.SUDOUEST,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Gironde,
  },
  {
    name: 'Hérault (34)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Herault,
  },
  {
    name: 'Ille-et-Vilaine (35)',
    zone: ZoneName.BRETAGNE,
    region: 'Bretagne',
    code: DepartmentCode.IlleEtVilaine,
  },
  {
    name: 'Indre (36)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.Indre,
  },
  {
    name: 'Indre-et-Loire (37)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.IndreEtLoire,
  },
  {
    name: 'Isère (38)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Isere,
  },
  {
    name: 'Jura (39)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Jura,
  },
  {
    name: 'Landes (40)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Landes,
  },
  {
    name: 'Loir-et-Cher (41)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.LoirEtCher,
  },
  {
    name: 'Loire (42)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Loire,
  },
  {
    name: 'Haute-Loire (43)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.HauteLoire,
  },
  {
    name: 'Loire-Atlantique (44)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.LoireAtlantique,
  },
  {
    name: 'Loiret (45)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.Loiret,
  },
  {
    name: 'Lot (46)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Lot,
  },
  {
    name: 'Lot-et-Garonne (47)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.LotEtGaronne,
  },
  {
    name: 'Lozère (48)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Lozere,
  },
  {
    name: 'Maine-et-Loire (49)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.MaineEtLoire,
  },
  {
    name: 'Manche (50)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Manche,
  },
  {
    name: 'Marne (51)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Marne,
  },
  {
    name: 'Haute-Marne (52)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.HauteMarne,
  },
  {
    name: 'Mayenne (53)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.Mayenne,
  },
  {
    name: 'Meurthe-et-Moselle (54)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.MeurtheEtMoselle,
  },
  {
    name: 'Meuse (55)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Meuse,
  },
  {
    name: 'Morbihan (56)',
    zone: ZoneName.LORIENT, // TODO: Change to BRETAGNE in the future
    region: 'Lorient',
    code: DepartmentCode.Morbihan,
  },
  {
    name: 'Moselle (57)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Moselle,
  },
  {
    name: 'Nièvre (58)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Nievre,
  },
  {
    name: 'Nord (59)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Nord,
  },
  {
    name: 'Oise (60)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Oise,
  },
  {
    name: 'Orne (61)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Orne,
  },
  {
    name: 'Pas-de-Calais (62)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.PasDeCalais,
  },
  {
    name: 'Puy-de-Dôme (63)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.PuyDeDome,
  },
  {
    name: 'Pyrénées-Atlantiques (64)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.PyreneesAtlantiques,
  },
  {
    name: 'Hautes-Pyrénées (65)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.HautesPyrenees,
  },
  {
    name: 'Pyrénées-Orientales (66)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.PyreneesOrientales,
  },
  {
    name: 'Bas-Rhin (67)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.BasRhin,
  },
  {
    name: 'Haut-Rhin (68)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.HautRhin,
  },
  {
    name: 'Rhône (69)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Rhone,
  },
  {
    name: 'Haute-Saône (70)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.HauteSaone,
  },
  {
    name: 'Saône-et-Loire (71)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.SaoneEtLoire,
  },
  {
    name: 'Sarthe (72)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.Sarthe,
  },
  {
    name: 'Savoie (73)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Savoie,
  },
  {
    name: 'Haute-Savoie (74)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.HauteSavoie,
  },
  {
    name: 'Paris (75)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.Paris,
  },
  {
    name: 'Seine-Maritime (76)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.SeineMaritime,
  },
  {
    name: 'Seine-et-Marne (77)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.SeineEtMarne,
  },
  {
    name: 'Yvelines (78)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.Yvelines,
  },
  {
    name: 'Deux-Sèvres (79)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.DeuxSevres,
  },
  {
    name: 'Somme (80)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Somme,
  },
  {
    name: 'Tarn (81)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Tarn,
  },
  {
    name: 'Tarn-et-Garonne (82)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.TarnEtGaronne,
  },
  {
    name: 'Var (83)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.Var,
  },
  {
    name: 'Vaucluse (84)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.Vaucluse,
  },
  {
    name: 'Vendée (85)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.Vendee,
  },
  {
    name: 'Vienne (86)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Vienne,
  },
  {
    name: 'Haute-Vienne (87)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.HauteVienne,
  },
  {
    name: 'Vosges (88)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Vosges,
  },
  {
    name: 'Yonne (89)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Yonne,
  },
  {
    name: 'Territoire de Belfort (90)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.TerritoireDeBelfort,
  },
  {
    name: 'Essonne (91)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.Essonne,
  },
  {
    name: 'Hauts-de-Seine (92)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.HautsDeSeine,
  },
  {
    name: 'Seine-Saint-Denis (93)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.SeineSaintDenis,
  },
  {
    name: 'Val-de-Marne (94)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.ValDeMarne,
  },
  {
    name: "Val-d'Oise (95)",
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.ValDOise,
  },
  {
    name: 'Guadeloupe (971)',
    zone: ZoneName.HZ,
    region: 'Guadeloupe',
    code: DepartmentCode.Guadeloupe,
  },
  {
    name: 'Martinique (972)',
    zone: ZoneName.HZ,
    region: 'Martinique',
    code: DepartmentCode.Martinique,
  },
  {
    name: 'Guyane (973)',
    zone: ZoneName.HZ,
    region: 'Guyane',
    code: DepartmentCode.Guyane,
  },
  {
    name: 'La Réunion (974)',
    zone: ZoneName.HZ,
    region: 'La Réunion',
    code: DepartmentCode.LaReunion,
  },
  {
    name: 'Mayotte (976)',
    zone: ZoneName.HZ,
    region: 'Mayotte',
    code: DepartmentCode.Mayotte,
  },
] as DepartmentType[];

export type Department = (typeof Departments)[number]['name'];

export const DepartmentFilters: FilterConstant<Department>[] = [
  ...Departments.map(({ name, zone }) => {
    return {
      value: name,
      label: name,
      zone,
    };
  }),
];
