import { FilterConstant } from 'src/utils/types';
import { DepartmentCode } from 'src/utils/types/departments.types';
import { ZoneName } from 'src/utils/types/zones.types';

export type DepartmentType = {
  name: string;
  zone: ZoneName;
  region: string;
  code: DepartmentCode;
  locative: string;
};

export const Departments: DepartmentType[] = [
  {
    name: 'Ain (01)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Ain,
    locative: "dans l'Ain",
  },
  {
    name: 'Aisne (02)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Aisne,
    locative: "dans l'Aisne",
  },
  {
    name: 'Allier (03)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Allier,
    locative: "dans l'Allier",
  },
  {
    name: 'Alpes-de-Haute-Provence (04)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.AlpesDeHauteProvence,
    locative: 'dans les Alpes-de-Haute-Provence',
  },
  {
    name: 'Hautes-Alpes (05)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.HautesAlpes,
    locative: 'dans les Hautes-Alpes',
  },
  {
    name: 'Alpes-Maritimes (06)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.AlpesMaritimes,
    locative: 'dans les Alpes-Maritimes',
  },
  {
    name: 'Ardèche (07)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Ardeche,
    locative: "dans l'Ardèche",
  },
  {
    name: 'Ardennes (08)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Ardennes,
    locative: 'dans les Ardennes',
  },
  {
    name: 'Ariège (09)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Ariege,
    locative: "dans l'Ariège",
  },
  {
    name: 'Aube (10)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Aube,
    locative: "dans l'Aube",
  },
  {
    name: 'Aude (11)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Aude,
    locative: "dans l'Aude",
  },
  {
    name: 'Aveyron (12)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Aveyron,
    locative: "dans l'Aveyron",
  },
  {
    name: 'Bouches-du-Rhône (13)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.BouchesDuRhone,
    locative: 'dans les Bouches-du-Rhône',
  },
  {
    name: 'Calvados (14)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Calvados,
    locative: 'dans le Calvados',
  },
  {
    name: 'Cantal (15)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Cantal,
    locative: 'dans le Cantal',
  },
  {
    name: 'Charente (16)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Charente,
    locative: 'dans la Charente',
  },
  {
    name: 'Charente-Maritime (17)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.CharenteMaritime,
    locative: 'dans la Charente-Maritime',
  },
  {
    name: 'Cher (18)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.Cher,
    locative: 'dans le Cher',
  },
  {
    name: 'Corrèze (19)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Correze,
    locative: 'dans la Corrèze',
  },
  {
    name: "Côte-d'Or (21)",
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.CoteDOr,
    locative: "dans la Côte-d'Or",
  },
  {
    name: "Côtes-d'Armor (22)",
    zone: ZoneName.BRETAGNE,
    region: 'Bretagne',
    code: DepartmentCode.CotesDArmor,
    locative: "dans les Côtes-d'Armor",
  },
  {
    name: 'Creuse (23)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Creuse,
    locative: 'dans la Creuse',
  },
  {
    name: 'Dordogne (24)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Dordogne,
    locative: 'dans la Dordogne',
  },
  {
    name: 'Doubs (25)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Doubs,
    locative: 'dans le Doubs',
  },
  {
    name: 'Drôme (26)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Drome,
    locative: 'dans la Drôme',
  },
  {
    name: 'Eure (27)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Eure,
    locative: "dans l'Eure",
  },
  {
    name: 'Eure-et-Loir (28)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.EureEtLoir,
    locative: "dans l'Eure-et-Loir",
  },
  {
    name: 'Finistère (29)',
    zone: ZoneName.BRETAGNE,
    region: 'Bretagne',
    code: DepartmentCode.Finistere,
    locative: 'dans le Finistère',
  },
  {
    name: 'Corse-du-Sud (2A)',
    zone: ZoneName.HZ,
    region: 'Corse',
    code: DepartmentCode.CorseDuSud,
    locative: 'dans la Corse-du-Sud',
  },
  {
    name: 'Haute-Corse (2B)',
    zone: ZoneName.HZ,
    region: 'Corse',
    code: DepartmentCode.HauteCorse,
    locative: 'dans la Haute-Corse',
  },
  {
    name: 'Gard (30)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Gard,
    locative: 'dans le Gard',
  },
  {
    name: 'Haute-Garonne (31)',
    zone: ZoneName.SUDOUEST,
    region: 'Occitanie',
    code: DepartmentCode.HauteGaronne,
    locative: 'dans la Haute-Garonne',
  },
  {
    name: 'Gers (32)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Gers,
    locative: 'dans le Gers',
  },
  {
    name: 'Gironde (33)',
    zone: ZoneName.SUDOUEST,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Gironde,
    locative: 'dans la Gironde',
  },
  {
    name: 'Hérault (34)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Herault,
    locative: "dans l'Hérault",
  },
  {
    name: 'Ille-et-Vilaine (35)',
    zone: ZoneName.BRETAGNE,
    region: 'Bretagne',
    code: DepartmentCode.IlleEtVilaine,
    locative: "dans l'Ille-et-Vilaine",
  },
  {
    name: 'Indre (36)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.Indre,
    locative: "dans l'Indre",
  },
  {
    name: 'Indre-et-Loire (37)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.IndreEtLoire,
    locative: "dans l'Indre-et-Loire",
  },
  {
    name: 'Isère (38)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Isere,
    locative: "dans l'Isère",
  },
  {
    name: 'Jura (39)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Jura,
    locative: 'dans le Jura',
  },
  {
    name: 'Landes (40)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Landes,
    locative: 'dans les Landes',
  },
  {
    name: 'Loir-et-Cher (41)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.LoirEtCher,
    locative: 'dans le Loir-et-Cher',
  },
  {
    name: 'Loire (42)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Loire,
    locative: 'dans la Loire',
  },
  {
    name: 'Haute-Loire (43)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.HauteLoire,
    locative: 'dans la Haute-Loire',
  },
  {
    name: 'Loire-Atlantique (44)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.LoireAtlantique,
    locative: 'dans la Loire-Atlantique',
  },
  {
    name: 'Loiret (45)',
    zone: ZoneName.HZ,
    region: 'Centre-Val de Loire',
    code: DepartmentCode.Loiret,
    locative: 'dans le Loiret',
  },
  {
    name: 'Lot (46)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Lot,
    locative: 'dans le Lot',
  },
  {
    name: 'Lot-et-Garonne (47)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.LotEtGaronne,
    locative: 'dans le Lot-et-Garonne',
  },
  {
    name: 'Lozère (48)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Lozere,
    locative: 'dans la Lozère',
  },
  {
    name: 'Maine-et-Loire (49)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.MaineEtLoire,
    locative: 'dans le Maine-et-Loire',
  },
  {
    name: 'Manche (50)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Manche,
    locative: 'dans la Manche',
  },
  {
    name: 'Marne (51)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Marne,
    locative: 'dans la Marne',
  },
  {
    name: 'Haute-Marne (52)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.HauteMarne,
    locative: 'dans la Haute-Marne',
  },
  {
    name: 'Mayenne (53)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.Mayenne,
    locative: 'dans la Mayenne',
  },
  {
    name: 'Meurthe-et-Moselle (54)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.MeurtheEtMoselle,
    locative: 'dans le Meurthe-et-Moselle',
  },
  {
    name: 'Meuse (55)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Meuse,
    locative: 'dans la Meuse',
  },
  {
    name: 'Morbihan (56)',
    zone: ZoneName.LORIENT,
    region: 'Lorient',
    code: DepartmentCode.Morbihan,
    locative: 'dans le Morbihan',
  }, // TODO: Change zone to BRETAGNE in the future
  {
    name: 'Moselle (57)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Moselle,
    locative: 'dans la Moselle',
  },
  {
    name: 'Nièvre (58)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Nievre,
    locative: 'dans la Nièvre',
  },
  {
    name: 'Nord (59)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Nord,
    locative: 'dans le Nord',
  },
  {
    name: 'Oise (60)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Oise,
    locative: "dans l'Oise",
  },
  {
    name: 'Orne (61)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.Orne,
    locative: "dans l'Orne",
  },
  {
    name: 'Pas-de-Calais (62)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.PasDeCalais,
    locative: 'dans le Pas-de-Calais',
  },
  {
    name: 'Puy-de-Dôme (63)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.PuyDeDome,
    locative: 'dans le Puy-de-Dôme',
  },
  {
    name: 'Pyrénées-Atlantiques (64)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.PyreneesAtlantiques,
    locative: 'dans les Pyrénées-Atlantiques',
  },
  {
    name: 'Hautes-Pyrénées (65)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.HautesPyrenees,
    locative: 'dans les Hautes-Pyrénées',
  },
  {
    name: 'Pyrénées-Orientales (66)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.PyreneesOrientales,
    locative: 'dans les Pyrénées-Orientales',
  },
  {
    name: 'Bas-Rhin (67)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.BasRhin,
    locative: 'dans le Bas-Rhin',
  },
  {
    name: 'Haut-Rhin (68)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.HautRhin,
    locative: 'dans le Haut-Rhin',
  },
  {
    name: 'Rhône (69)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Rhone,
    locative: 'dans le Rhône',
  },
  {
    name: 'Haute-Saône (70)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.HauteSaone,
    locative: 'dans la Haute-Saône',
  },
  {
    name: 'Saône-et-Loire (71)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.SaoneEtLoire,
    locative: 'dans la Saône-et-Loire',
  },
  {
    name: 'Sarthe (72)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.Sarthe,
    locative: 'dans la Sarthe',
  },
  {
    name: 'Savoie (73)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.Savoie,
    locative: 'dans la Savoie',
  },
  {
    name: 'Haute-Savoie (74)',
    zone: ZoneName.AURA,
    region: 'Auvergne-Rhône-Alpes',
    code: DepartmentCode.HauteSavoie,
    locative: 'dans la Haute-Savoie',
  },
  {
    name: 'Paris (75)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.Paris,
    locative: 'à Paris',
  },
  {
    name: 'Seine-Maritime (76)',
    zone: ZoneName.HZ,
    region: 'Normandie',
    code: DepartmentCode.SeineMaritime,
    locative: 'dans la Seine-Maritime',
  },
  {
    name: 'Seine-et-Marne (77)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.SeineEtMarne,
    locative: 'dans la Seine-et-Marne',
  },
  {
    name: 'Yvelines (78)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.Yvelines,
    locative: 'dans les Yvelines',
  },
  {
    name: 'Deux-Sèvres (79)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.DeuxSevres,
    locative: 'dans les Deux-Sèvres',
  },
  {
    name: 'Somme (80)',
    zone: ZoneName.NORD,
    region: 'Hauts-de-France',
    code: DepartmentCode.Somme,
    locative: 'dans la Somme',
  },
  {
    name: 'Tarn (81)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.Tarn,
    locative: 'dans le Tarn',
  },
  {
    name: 'Tarn-et-Garonne (82)',
    zone: ZoneName.HZ,
    region: 'Occitanie',
    code: DepartmentCode.TarnEtGaronne,
    locative: 'dans le Tarn-et-Garonne',
  },
  {
    name: 'Var (83)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.Var,
    locative: 'dans le Var',
  },
  {
    name: 'Vaucluse (84)',
    zone: ZoneName.HZ,
    region: "Provence-Alpes-Côte d'Azur",
    code: DepartmentCode.Vaucluse,
    locative: 'dans le Vaucluse',
  },
  {
    name: 'Vendée (85)',
    zone: ZoneName.HZ,
    region: 'Pays de la Loire',
    code: DepartmentCode.Vendee,
    locative: 'dans la Vendée',
  },
  {
    name: 'Vienne (86)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.Vienne,
    locative: 'dans la Vienne',
  },
  {
    name: 'Haute-Vienne (87)',
    zone: ZoneName.HZ,
    region: 'Nouvelle-Aquitaine',
    code: DepartmentCode.HauteVienne,
    locative: 'dans la Haute-Vienne',
  },
  {
    name: 'Vosges (88)',
    zone: ZoneName.HZ,
    region: 'Grand Est',
    code: DepartmentCode.Vosges,
    locative: 'dans les Vosges',
  },
  {
    name: 'Yonne (89)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.Yonne,
    locative: "dans l'Yonne",
  },
  {
    name: 'Territoire de Belfort (90)',
    zone: ZoneName.HZ,
    region: 'Bourgogne-Franche-Comté',
    code: DepartmentCode.TerritoireDeBelfort,
    locative: 'dans le Territoire de Belfort',
  },
  {
    name: 'Essonne (91)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.Essonne,
    locative: "dans l'Essonne",
  },
  {
    name: 'Hauts-de-Seine (92)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.HautsDeSeine,
    locative: 'dans les Hauts-de-Seine',
  },
  {
    name: 'Seine-Saint-Denis (93)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.SeineSaintDenis,
    locative: 'dans la Seine-Saint-Denis',
  },
  {
    name: 'Val-de-Marne (94)',
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.ValDeMarne,
    locative: 'dans le Val-de-Marne',
  },
  {
    name: "Val-d'Oise (95)",
    zone: ZoneName.IDF,
    region: 'Île-de-France',
    code: DepartmentCode.ValDOise,
    locative: "dans le Val-d'Oise",
  },
  {
    name: 'Guadeloupe (971)',
    zone: ZoneName.HZ,
    region: 'Guadeloupe',
    code: DepartmentCode.Guadeloupe,
    locative: 'en Guadeloupe',
  },
  {
    name: 'Martinique (972)',
    zone: ZoneName.HZ,
    region: 'Martinique',
    code: DepartmentCode.Martinique,
    locative: 'en Martinique',
  },
  {
    name: 'Guyane (973)',
    zone: ZoneName.HZ,
    region: 'Guyane',
    code: DepartmentCode.Guyane,
    locative: 'en Guyane',
  },
  {
    name: 'La Réunion (974)',
    zone: ZoneName.HZ,
    region: 'La Réunion',
    code: DepartmentCode.LaReunion,
    locative: 'à La Réunion',
  },
  {
    name: 'Mayotte (976)',
    zone: ZoneName.HZ,
    region: 'Mayotte',
    code: DepartmentCode.Mayotte,
    locative: 'à Mayotte',
  },
];

export type Department = (typeof Departments)[number]['name'];

export const DepartmentFilters: FilterConstant<Department>[] = [
  ...Departments.map(({ name, zone }) => {
    return {
      value: name,
      label: name,
      zone,
    };
  }),
];
