name: LinkedOut Backend Test

on:
  push:
    branches: [master, develop]
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: entourage-job-back-test

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: linkedout
          POSTGRES_USER: linkedout
          POSTGRES_DB: linkedout
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      CI: true
      NODE_ENV: test
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn install
      - run: yarn db:migrate
      - run: yarn test:e2e
